---
title: "Working Papers"
format: html
editor: visual
---

**Leveraging Natural Language Processing to Analyze Narrative Structure in U.S. Space Policy**

*Cheyenne Black, Jon Ruff*

Natural language processors (NLPs) have grown in interest in public policy analysis as tools to improve the efficiency of qualitative research practices. This paper examines the utility of NLPs in the context of US space policy Congressional documents detailing commercialization. As a low-salience arena, space policy offers a unique opportunity to test NLPs within complex and technical distinctions in language. Past attempts at adopting NLPs in policy process research have demonstrated difficulties with complex policy designs. This paper adopts a theoretical construction to aid the machine learning process through established categorization by identifying narrative elements in policy storytelling. Policy narratives, stories that define problems, solutions, and actors, play a critical role in framing policy debates. Using the Narrative Policy Framework (NPF), a policy process framework distinguishing the core elements of policy narratives, this article adopts NLPs to test the resiliency of machine learning and improve the capacity of the NPF to capture a troublesome narrative element, and central construct of policy narratives: Plot. By adopting machine learning techniques, the paper develops a framework to automate the qualitative coding of narrative plots across large collections of U.S. space policy texts. The analysis explores three dimensions of the narrative plot: (1) sequential structure, which examines the order and progression of the narrative; (2) valence, which assesses the positive or negative tone attributed to policy actors and outcomes; and (3) causal attribution, which identifies how responsibility for outcomes is assigned by the narrator. By applying natural language processing (NLP) algorithms, the study uncovers recurring patterns and themes across US space policy narratives, highlighting how policy actors construct and communicate visions of the future of space exploration, governance, and international collaboration.The findings demonstrate that machine learning approaches offer a scalable and efficient method for analyzing complex topics and narrative structures, providing valuable insights for researchers, policymakers, and institutions seeking to understand the framing of space policy.

**Let there be light? Partisanship differences in light pollution mitigation strategies**

*Cheyenne A. Black, Andrew Fox, Maggie Leon-Corwin, Hank Jenkins-Smith, Carol Silva*

Light pollution is rising with suburban expansion, impacting ecosystems, astronomy, and public health. Despite scientific concern, it remains largely absent from federal and state policy agendas, with most regulations enacted locally. As awareness grows, light pollution policy may follow other environmental issues, subject to partisan polarization and shifts in public salience. Using the first national survey on U.S. light pollution policy preferences (N=4,994), this study examines public support for mitigation strategies, including government intervention, market-based solutions, and individual autonomy. While partisan divides shape preferences, particularly for government regulation, bipartisan agreement exists on technological innovation and public awareness campaigns. Both Democrats and Republicans moderately support local and state government, the National Park Service, and individuals in mitigation efforts, though Democrats favor stronger institutional action. These findings highlight opportunities for sustainable, politically feasible light pollution policies within a polarized policy landscape.

**The Color of Risk: Insights from a Scoping Review of Color Usage in Risk Visualizations**

*Joseph Ripberger, Angela Person, Cheyenne A. Black, Sarah Melcher, Zoey Rosen, Abby Bitterman*

The use of color in risk communication plays a crucial role in decision-making and behavioral responses across domains like disaster preparedness, financial risk management and public health. This scoping review systematically maps 112 peer-reviewed studies to provide an overview of research on the use of color in risk visualizations, identify trends, and highlight gaps to inform future research directions. The review identifies primary research themes of performance testing, visualization preference, influencing behavioral intent or protective action, perceived risk, and specific color association in color risk communication research. We examine common research domains, visualization types, and methods used in this body of research, finding that quantitative and experimental approaches are widely used and often conducted in lab settings. Results indicate thematic co-occurrence of studies focusing on visualization preference and performance testing and the presence of gaps in methodological diversity, accessibility considerations, and generalizability. A bibliometric analysis conducted of studies reveal the field of color in risk communication is expanding, but still fragmented with weak citation integration across all studies. Based on this review, we propose recommendations for expanding color in risk communication research by incorporating more mixed-methods and qualitative approaches, incorporating more user-centered research designs, broadening research contexts, and increasing literature integration in studies.

**Public attitudes and perspectives on the trade-offs associated with limiting nighttime lighting**

*Andrew Fox, Maggie Leon-Corwin, Hank Jenkins-Smith, Carol Silva, Cheyenne A. Black, Jeffrey Kelly, Kyle Horton, Carolyn Burt, Ali Khalighifar, Grace Trankina*

1\. Artificial light at night (ALAN) is associated with improved standards of living and a range of perceived benefits, including reduced crime and fewer traffic accidents; however, ALAN also has a negative impact on both the natural environment and human health. 2. Empirical evidence documenting the ecological impacts of ALAN has resulted in identification of potential solutions for mitigating the adverse effects of nighttime lighting, such as shifting the spectra of lighting and changing behavioral patterns of use. The effectiveness of these solutions is unclear, and widespread implementation would likely depend social and political feasibility, which remain unexplored. 3. Using data from a nationally representative survey (N = 4,994), we find moderate support for reducing outdoor lighting; however, garnering public support is contingent upon and influenced by risk and benefit perceptions as well as tradeoffs between personal choice, the importance of being able to see the night sky, and concern for the environment.

**Nuclear Weapon Policy Beliefs Overtime: An Assessment of Cultural Theory and Ideology Measurement Consistency**

*Cheyenne A. Black, Katie Peach, Kaitlin Diodosio, Joseph Ripberger, Kuhika Gupta, Hank Jenkins-Smith*

In national security policy, as in other policy domains, coalitions of individuals and organizations participating in the policy process form based on their beliefs and policy preferences. The stability of these beliefs over time influences this process. Drawing upon measures of Cultural Theory and ideology from a nationally representative survey, we reexamine previous methods of measuring belief systems related to nuclear weapons policy and examine their stability over time. Our analysis pairs Cultural Theory and ideology responses with opinions on nuclear weapons to assess the stability of deep-core beliefs over eight-years (2016-2023). Focusing on this unique policy area, we reevaluate measuring beliefs under the Advocacy Coalition Framework. Results demonstrate conservative ideology has a consistently positive and significant relationship with the expressed importance of nuclear arsenal retention policy. Of Cultural Theory measures, Hierarchism is the most consistently related to policy elites’ increased nuclear retention policy beliefs. Other Cultural Theory measures are not as consistent across the eight years observed. When significant, Egalitarians are less supportive of nuclear arsenal retention while individualists are supportive. Fatalists are consistently not significant to their nuclear arsenal retention beliefs. This approach demonstrates that using an ideological indicator of deep core policy beliefs hides variation made visible through the use of Cultural Theory measures, illustrating the value cultural theory measures provide.
